import { config } from 'dotenv';
import { db } from '../lib/db';

// Carregar variáveis de ambiente
config({ path: '../.env.local' });

async function seedDatabase() {
  console.log('Iniciando seed do banco de dados...');

  // Dados de exemplo para restaurantes
  const restaurantes = [
    {
      id: 'rest-001',
      nome: 'Pizza Bella',
      cnpj: '12.345.678/0001-90',
      email: 'contato@pizzabella.com',
      telefone: '(11) 99999-0001',
      endereco: 'Rua das Pizzas, 123, São Paulo, SP',
      latitude: -23.5505,
      longitude: -46.6333,
      categoria: 'Italiana',
      descricao: 'As melhores pizzas artesanais da cidade',
      logo: '/logos/pizza-bella.png',
      capa: '/capas/pizza-bella.jpg',
      status: 'ativo',
      taxa_comissao: 15,
      tempo_medio_preparo: 30,
    },
    {
      id: 'rest-002',
      nome: 'Burger House',
      cnpj: '98.765.432/0001-10',
      email: 'info@burgerhouse.com',
      telefone: '(11) 99999-0002',
      endereco: 'Av. dos Hambúrgueres, 456, São Paulo, SP',
      latitude: -23.5515,
      longitude: -46.6343,
      categoria: 'Americana',
      descricao: 'Hambúrgueres gourmet feitos com ingredientes frescos',
      logo: '/logos/burger-house.png',
      capa: '/capas/burger-house.jpg',
      status: 'ativo',
      taxa_comissao: 15,
      tempo_medio_preparo: 20,
    },
    {
      id: 'rest-003',
      nome: 'Sushi Express',
      cnpj: '11.222.333/0001-44',
      email: 'hello@sushiexpress.com',
      telefone: '(11) 99999-0003',
      endereco: 'Rua Oriental, 789, São Paulo, SP',
      latitude: -23.5525,
      longitude: -46.6353,
      categoria: 'Japonesa',
      descricao: 'Sushi fresco e delivery rápido',
      logo: '/logos/sushi-express.png',
      capa: '/capas/sushi-express.jpg',
      status: 'ativo',
      taxa_comissao: 15,
      tempo_medio_preparo: 25,
    },
    {
      id: 'rest-004',
      nome: 'Café & Cia',
      cnpj: '55.666.777/0001-88',
      email: 'cafe@cafecia.com',
      telefone: '(11) 99999-0004',
      endereco: 'Praça do Café, 321, São Paulo, SP',
      latitude: -23.5535,
      longitude: -46.6363,
      categoria: 'Cafeteria',
      descricao: 'Café especial e doces artesanais',
      logo: '/logos/cafe-cia.png',
      capa: '/capas/cafe-cia.jpg',
      status: 'ativo',
      taxa_comissao: 15,
      tempo_medio_preparo: 15,
    },
    {
      id: 'rest-005',
      nome: 'Taco Loco',
      cnpj: '99.888.777/0001-66',
      email: 'tacos@tacoloco.com',
      telefone: '(11) 99999-0005',
      endereco: 'Rua Mexicana, 654, São Paulo, SP',
      latitude: -23.5545,
      longitude: -46.6373,
      categoria: 'Mexicana',
      descricao: 'Autênticos tacos e burritos mexicanos',
      logo: '/logos/taco-loco.png',
      capa: '/capas/taco-loco.jpg',
      status: 'ativo',
      taxa_comissao: 15,
      tempo_medio_preparo: 20,
    },
  ];

  // Inserir restaurantes
  for (const restaurante of restaurantes) {
    await db.execute({
      sql: `INSERT OR REPLACE INTO restaurantes (id, nome, cnpj, email, telefone, endereco, latitude, longitude, categoria, descricao, logo, capa, status, taxa_comissao, tempo_medio_preparo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        restaurante.id,
        restaurante.nome,
        restaurante.cnpj,
        restaurante.email,
        restaurante.telefone,
        restaurante.endereco,
        restaurante.latitude,
        restaurante.longitude,
        restaurante.categoria,
        restaurante.descricao,
        restaurante.logo,
        restaurante.capa,
        restaurante.status,
        restaurante.taxa_comissao,
        restaurante.tempo_medio_preparo,
      ],
    });
  }

  console.log('Restaurantes inseridos com sucesso!');

  // Dados de exemplo para cardápios
  const cardapios = [
    // Pizza Bella
    {
      id: 'item-001',
      restaurante_id: 'rest-001',
      nome: 'Pizza Margherita',
      descricao: 'Molho de tomate, mussarela, manjericão fresco',
      preco: 35.90,
      categoria: 'Pizzas',
      subcategoria: 'Tradicional',
      imagem: '/cardapio/pizza-margherita.jpg',
      ingredientes: 'Molho de tomate, mussarela, manjericão',
      disponivel: true,
      destaque: true,
      tempo_preparo: 25,
    },
    {
      id: 'item-002',
      restaurante_id: 'rest-001',
      nome: 'Pizza Calabresa',
      descricao: 'Molho de tomate, mussarela, calabresa, cebola',
      preco: 38.90,
      categoria: 'Pizzas',
      subcategoria: 'Tradicional',
      imagem: '/cardapio/pizza-calabresa.jpg',
      ingredientes: 'Molho de tomate, mussarela, calabresa, cebola',
      disponivel: true,
      destaque: false,
      tempo_preparo: 25,
    },
    {
      id: 'item-003',
      restaurante_id: 'rest-001',
      nome: 'Pizza Quatro Queijos',
      descricao: 'Mussarela, provolone, parmesão, gorgonzola',
      preco: 42.90,
      categoria: 'Pizzas',
      subcategoria: 'Especial',
      imagem: '/cardapio/pizza-quatro-queijos.jpg',
      ingredientes: 'Mussarela, provolone, parmesão, gorgonzola',
      disponivel: true,
      destaque: true,
      tempo_preparo: 30,
    },

    // Burger House
    {
      id: 'item-004',
      restaurante_id: 'rest-002',
      nome: 'Classic Burger',
      descricao: 'Pão brioche, 180g de carne, queijo cheddar, alface, tomate',
      preco: 28.90,
      categoria: 'Hambúrgueres',
      subcategoria: 'Clássicos',
      imagem: '/cardapio/classic-burger.jpg',
      ingredientes: 'Pão brioche, carne bovina 180g, queijo cheddar, alface, tomate, maionese',
      disponivel: true,
      destaque: true,
      tempo_preparo: 15,
    },
    {
      id: 'item-005',
      restaurante_id: 'rest-002',
      nome: 'Bacon Burger',
      descricao: 'Pão brioche, 180g de carne, bacon crocante, queijo cheddar',
      preco: 32.90,
      categoria: 'Hambúrgueres',
      subcategoria: 'Clássicos',
      imagem: '/cardapio/bacon-burger.jpg',
      ingredientes: 'Pão brioche, carne bovina 180g, bacon, queijo cheddar, alface, tomate',
      disponivel: true,
      destaque: false,
      tempo_preparo: 15,
    },
    {
      id: 'item-006',
      restaurante_id: 'rest-002',
      nome: 'Onion Rings',
      descricao: 'Anéis de cebola empanados e fritos',
      preco: 12.90,
      categoria: 'Acompanhamentos',
      subcategoria: 'Fritos',
      imagem: '/cardapio/onion-rings.jpg',
      ingredientes: 'Cebola, farinha de trigo, óleo',
      disponivel: true,
      destaque: false,
      tempo_preparo: 10,
    },

    // Sushi Express
    {
      id: 'item-007',
      restaurante_id: 'rest-003',
      nome: 'Sushi Combo 20 peças',
      descricao: '10 sushis e 10 sashimis variados',
      preco: 45.90,
      categoria: 'Combos',
      subcategoria: 'Sushi',
      imagem: '/cardapio/sushi-combo.jpg',
      ingredientes: 'Arroz, alga nori, salmão, atum, peixe branco',
      disponivel: true,
      destaque: true,
      tempo_preparo: 20,
    },
    {
      id: 'item-008',
      restaurante_id: 'rest-003',
      nome: 'Temaki Salmão',
      descricao: 'Cone de alga nori recheado com salmão fresco',
      preco: 18.90,
      categoria: 'Temaki',
      subcategoria: 'Salmão',
      imagem: '/cardapio/temaki-salmao.jpg',
      ingredientes: 'Alga nori, arroz, salmão, cream cheese',
      disponivel: true,
      destaque: false,
      tempo_preparo: 15,
    },
    {
      id: 'item-009',
      restaurante_id: 'rest-003',
      nome: 'Yakisoba',
      descricao: 'Macarrão frito com legumes e carne',
      preco: 22.90,
      categoria: 'Pratos Quentes',
      subcategoria: 'Macarrão',
      imagem: '/cardapio/yakisoba.jpg',
      ingredientes: 'Macarrão, carne, brócolis, cenoura, cebola, molho yakisoba',
      disponivel: true,
      destaque: false,
      tempo_preparo: 20,
    },

    // Café & Cia
    {
      id: 'item-010',
      restaurante_id: 'rest-004',
      nome: 'Café Espresso',
      descricao: 'Café espresso tradicional italiano',
      preco: 5.90,
      categoria: 'Bebidas',
      subcategoria: 'Café',
      imagem: '/cardapio/cafe-espresso.jpg',
      ingredientes: 'Café moído, água quente',
      disponivel: true,
      destaque: true,
      tempo_preparo: 5,
    },
    {
      id: 'item-011',
      restaurante_id: 'rest-004',
      nome: 'Croissant',
      descricao: 'Croissant folhado francês',
      preco: 8.90,
      categoria: 'Padaria',
      subcategoria: 'Pães',
      imagem: '/cardapio/croissant.jpg',
      ingredientes: 'Farinha, manteiga, leite, açúcar',
      disponivel: true,
      destaque: false,
      tempo_preparo: 10,
    },
    {
      id: 'item-012',
      restaurante_id: 'rest-004',
      nome: 'Torta de Maçã',
      descricao: 'Torta de maçã caseira com canela',
      preco: 15.90,
      categoria: 'Doces',
      subcategoria: 'Tortas',
      imagem: '/cardapio/torta-maca.jpg',
      ingredientes: 'Maçã, farinha, açúcar, canela, manteiga',
      disponivel: true,
      destaque: true,
      tempo_preparo: 15,
    },

    // Taco Loco
    {
      id: 'item-013',
      restaurante_id: 'rest-005',
      nome: 'Taco Al Pastor',
      descricao: 'Taco com carne de porco marinada, abacaxi, cebola',
      preco: 12.90,
      categoria: 'Tacos',
      subcategoria: 'Carne',
      imagem: '/cardapio/taco-al-pastor.jpg',
      ingredientes: 'Tortilla, carne de porco, abacaxi, cebola, coentro',
      disponivel: true,
      destaque: true,
      tempo_preparo: 15,
    },
    {
      id: 'item-014',
      restaurante_id: 'rest-005',
      nome: 'Burrito Chicken',
      descricao: 'Burrito recheado com frango, arroz, feijão, queijo',
      preco: 18.90,
      categoria: 'Burritos',
      subcategoria: 'Frango',
      imagem: '/cardapio/burrito-chicken.jpg',
      ingredientes: 'Tortilla, frango, arroz, feijão, queijo, sour cream',
      disponivel: true,
      destaque: false,
      tempo_preparo: 20,
    },
    {
      id: 'item-015',
      restaurante_id: 'rest-005',
      nome: 'Quesadilla',
      descricao: 'Tortilla recheada com queijo e vegetais',
      preco: 14.90,
      categoria: 'Quesadillas',
      subcategoria: 'Vegetariana',
      imagem: '/cardapio/quesadilla.jpg',
      ingredientes: 'Tortilla, queijo, pimentão, cebola, abacate',
      disponivel: true,
      destaque: false,
      tempo_preparo: 10,
    },
  ];

  // Inserir cardápios
  for (const item of cardapios) {
    await db.execute({
      sql: `INSERT OR REPLACE INTO cardapio (id, restaurante_id, nome, descricao, preco, categoria, subcategoria, imagem, ingredientes, disponivel, destaque, tempo_preparo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        item.id,
        item.restaurante_id,
        item.nome,
        item.descricao,
        item.preco,
        item.categoria,
        item.subcategoria,
        item.imagem,
        item.ingredientes,
        item.disponivel ? 1 : 0,
        item.destaque ? 1 : 0,
        item.tempo_preparo,
      ],
    });
  }

  console.log('Cardápios inseridos com sucesso!');
  console.log('Seed concluído!');
}

seedDatabase().catch(console.error);